2012/10/24 21:22:52 [error] [exception.Exception] exception 'Exception' with message 'This method only supports the `php` response format' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/extensions/dropbox/API.php:267
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php(41): Dropbox_API->thumbnails('/ProyectoDesarr...', 'image/png', 'dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/actions/CInlineAction.php(50): DropboxController->actionIndex()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('')
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox')
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:23:09 [error] [exception.Exception] exception 'Exception' with message 'This method only supports the `php` response format' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/extensions/dropbox/API.php:267
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php(41): Dropbox_API->thumbnails('/ProyectoDesarr...', 'image/png')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/actions/CInlineAction.php(50): DropboxController->actionIndex()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('')
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox')
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:24:34 [error] [exception.Exception] exception 'Exception' with message 'This method only supports the `php` response format' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/extensions/dropbox/API.php:267
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php(41): Dropbox_API->thumbnails('/ProyectoDesarr...', 'image/png', 'small')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/actions/CInlineAction.php(50): DropboxController->actionIndex()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('')
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox')
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:25:01 [error] [exception.Exception] exception 'Exception' with message 'This method only supports the `php` response format' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/extensions/dropbox/API.php:267
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php(41): Dropbox_API->thumbnails('/ProyectoDesarr...', 'PNG', 'small')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/actions/CInlineAction.php(50): DropboxController->actionIndex()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('')
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox')
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:37:13 [error] [php] Cannot modify header information - headers already sent by (output started at /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php:30) (/Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php:42)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(309): CInlineAction->runWithParams()
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(287): DropboxController->runAction()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): DropboxController->runActionWithFilters()
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): DropboxController->run()
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController()
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CWebApplication->run()
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox
in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php (42)
in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php (13)
2012/10/24 21:40:35 [error] [php] Cannot modify header information - headers already sent by (output started at /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php:2) (/Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php:2)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(277): CWebApplication->createController()
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CWebApplication->run()
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox
in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php (2)
in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php (13)
2012/10/24 21:40:36 [error] [php] Cannot modify header information - headers already sent by (output started at /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php:2) (/Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php:2)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(277): CWebApplication->createController()
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CWebApplication->run()
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox
in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php (2)
in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php (13)
2012/10/24 21:40:38 [error] [php] Cannot modify header information - headers already sent by (output started at /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php:2) (/Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php:2)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(277): CWebApplication->createController()
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CWebApplication->run()
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox
in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php (2)
in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php (13)
2012/10/24 21:40:58 [error] [php] Cannot modify header information - headers already sent by (output started at /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php:2) (/Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php:2)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(277): CWebApplication->createController()
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CWebApplication->run()
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox
in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php (2)
in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php (13)
2012/10/24 21:41:12 [error] [php] Cannot modify header information - headers already sent by (output started at /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php:30) (/Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php:42)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(309): CInlineAction->runWithParams()
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(287): DropboxController->runAction()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): DropboxController->runActionWithFilters()
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): DropboxController->run()
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController()
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CWebApplication->run()
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox
in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php (42)
in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php (13)
2012/10/24 21:49:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "android-1.png/img/error.gif"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('android-1.png/i...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/android-1.png/img/error.gif
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:49:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "100px-Blender_2.5_Icon_Pixmap_for_Gnome.png/img/error.gif"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('100px-Blender_2...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/100px-Blender_2.5_Icon_Pixmap_for_Gnome.png/img/error.gif
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:49:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "android-logo-font.png/img/error.gif"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('android-logo-fo...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/android-logo-font.png/img/error.gif
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:49:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "android-logo-font54.png/img/error.gif"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('android-logo-fo...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/android-logo-font54.png/img/error.gif
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:49:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "Friday Tag Game.jpg/img/error.gif"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('Friday Tag Game...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/Friday%20Tag%20Game.jpg/img/error.gif
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:49:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "Android-2.png/img/error.gif"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('Android-2.png/i...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/Android-2.png/img/error.gif
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:50:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "Android-2.png"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('Android-2.png')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/Android-2.png/
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:50:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "100px-Blender_2.5_Icon_Pixmap_for_Gnome.png"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('100px-Blender_2...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/100px-Blender_2.5_Icon_Pixmap_for_Gnome.png/
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:50:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "Friday Tag Game.jpg"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('Friday Tag Game...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/Friday%20Tag%20Game.jpg/
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:50:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "android-logo-font.png"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('android-logo-fo...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/android-logo-font.png/
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:50:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "android-1.png"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('android-1.png')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/android-1.png/
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:50:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "android-logo-font54.png"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('android-logo-fo...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/android-logo-font54.png/
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:51:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "100px-Blender_2.5_Icon_Pixmap_for_Gnome.png"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('100px-Blender_2...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/100px-Blender_2.5_Icon_Pixmap_for_Gnome.png
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:51:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "Friday Tag Game.jpg"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('Friday Tag Game...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/Friday%20Tag%20Game.jpg
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:51:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "android-logo-font54.png"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('android-logo-fo...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/android-logo-font54.png
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:51:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "android-logo-font.png"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('android-logo-fo...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/android-logo-font.png
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:51:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "android-1.png"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('android-1.png')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/android-1.png
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:51:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "Android-2.png"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('Android-2.png')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/Android-2.png
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:52:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "100px-Blender_2.5_Icon_Pixmap_for_Gnome.png"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('100px-Blender_2...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/100px-Blender_2.5_Icon_Pixmap_for_Gnome.png
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:52:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "Android-2.png"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('Android-2.png')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/Android-2.png
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:52:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "android-1.png"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('android-1.png')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/android-1.png
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:52:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "android-logo-font.png"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('android-logo-fo...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/android-logo-font.png
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:52:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "Friday Tag Game.jpg"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('Friday Tag Game...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/Friday%20Tag%20Game.jpg
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 21:52:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "android-logo-font54.png"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('android-logo-fo...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/android-logo-font54.png
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/dropbox
---
2012/10/24 22:18:42 [error] [exception.Dropbox_Exception_Forbidden] exception 'Dropbox_Exception_Forbidden' with message 'Forbidden.
						This could mean a bad OAuth request, or a file or folder already existing at the target location.
						Invalid or missing signature
' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/extensions/dropbox/OAuth/Curl.php:124
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/extensions/dropbox/API.php(267): Dropbox_OAuth_Curl->fetch('https://api-con...', Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php(42): Dropbox_API->getThumbnail('/ProyectoDesarr...', 'small')
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/actions/CInlineAction.php(50): DropboxController->actionIndex()
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('')
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox')
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox
---
2012/10/25 17:46:34 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:337
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(310): CController->invalidActionParams(Object(CInlineAction))
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilter.php(41): CFilterChain->run()
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(292): CFilterChain->run()
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('view')
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('usuario/view')
#10 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/usuario/view
---
2012/10/25 17:46:43 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:337
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(310): CController->invalidActionParams(Object(CInlineAction))
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilter.php(41): CFilterChain->run()
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(292): CFilterChain->run()
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('view')
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('usuario/view')
#10 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/usuario/view
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/site/login
---
2012/10/25 17:47:26 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:337
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(310): CController->invalidActionParams(Object(CInlineAction))
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilter.php(41): CFilterChain->run()
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(292): CFilterChain->run()
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('view')
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('usuario/view')
#10 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/usuario/view
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/site/login
---
2012/10/25 17:47:29 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:337
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(310): CController->invalidActionParams(Object(CInlineAction))
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilter.php(41): CFilterChain->run()
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(292): CFilterChain->run()
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('view')
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('usuario/view')
#10 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/usuario/view
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/site/login
---
2012/10/25 17:47:29 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:337
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(310): CController->invalidActionParams(Object(CInlineAction))
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilter.php(41): CFilterChain->run()
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(292): CFilterChain->run()
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('view')
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('usuario/view')
#10 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/usuario/view
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/site/login
---
2012/10/25 17:47:29 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:337
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(310): CController->invalidActionParams(Object(CInlineAction))
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilter.php(41): CFilterChain->run()
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(292): CFilterChain->run()
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('view')
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('usuario/view')
#10 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/usuario/view
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/site/login
---
2012/10/25 17:47:36 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/auth/CAccessControlFilter.php:170
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/auth/CAccessControlFilter.php(133): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(292): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('usuario/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/usuario/admin
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/usuario/
---
2012/10/25 17:47:41 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:337
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(310): CController->invalidActionParams(Object(CInlineAction))
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilter.php(41): CFilterChain->run()
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(292): CFilterChain->run()
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('view')
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('usuario/view')
#10 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/usuario/view
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/site/login
---
2012/10/25 17:47:50 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:337
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(310): CController->invalidActionParams(Object(CInlineAction))
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilter.php(41): CFilterChain->run()
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(292): CFilterChain->run()
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('view')
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('usuario/view')
#10 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#11 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/usuario/view
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/site/login
---
2012/10/25 17:49:11 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/auth/CAccessControlFilter.php:170
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/auth/CAccessControlFilter.php(133): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(292): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('usuario/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/usuario/admin
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/usuario/
---
2012/10/25 17:49:53 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/auth/CAccessControlFilter.php:170
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/auth/CAccessControlFilter.php(133): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(292): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('usuario/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/usuario/admin
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/usuario/
---
2012/10/25 17:50:14 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/auth/CAccessControlFilter.php:170
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/auth/CAccessControlFilter.php(133): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(292): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('usuario/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/usuario/admin
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/usuario/
---
2012/10/25 17:50:43 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/auth/CAccessControlFilter.php:170
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/auth/CAccessControlFilter.php(133): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(292): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('usuario/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/usuario/admin
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/usuario/
---
2012/10/25 18:42:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox...')
#3 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/ProyectoDesarrollo/index.php/dropbox/dropbox/Authorize
---
2012/10/25 18:42:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox...')
#3 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/ProyectoDesarrollo/index.php/dropbox/dropbox/Authorize
---
2012/10/25 18:42:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox...')
#3 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/ProyectoDesarrollo/index.php/dropbox/dropbox/Authorize
HTTP_REFERER=http://localhost/ProyectoDesarrollo/index.php/site/login
---
2012/10/25 18:43:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox...')
#3 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/ProyectoDesarrollo/index.php/dropbox/dropbox/Authorize
---
2012/10/25 18:44:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox...')
#3 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/ProyectoDesarrollo/index.php/dropbox/dropbox/Authorize
---
2012/10/25 18:45:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox')
#3 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/ProyectoDesarrollo/index.php/dropbox/dropbox/
---
2012/10/25 18:47:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox...')
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox/dropbox/Authorize
---
2012/10/25 18:48:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox...')
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox/dropbox/Authorize
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/site/login
---
2012/10/25 19:00:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "Authorize"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('Authorize')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/Authorize
---
2012/10/25 19:00:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "Authorize"' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php:287
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('Authorize')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/Authorize
---
2012/10/25 19:03:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/auth/CAccessControlFilter.php:170
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/auth/CAccessControlFilter.php(133): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(292): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('page')
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('site/page')
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/site/page?view=about
HTTP_REFERER=http://localhost/proyectoDesarrollo/
---
2012/10/25 19:03:56 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/auth/CAccessControlFilter.php:170
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/auth/CAccessControlFilter.php(133): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(292): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('page')
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('site/page')
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/site/page?view=about
HTTP_REFERER=http://localhost/proyectoDesarrollo/
---
2012/10/25 19:04:12 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/auth/CAccessControlFilter.php:170
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/auth/CAccessControlFilter.php(133): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(292): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CViewAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('page')
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('site/page')
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/site/page?view=about
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/
---
2012/10/25 19:04:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox...')
#3 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/ProyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/ProyectoDesarrollo/index.php/dropbox/dropbox/Authorize
---
2012/10/25 19:04:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox...')
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox/dropbox/Authorize
---
2012/10/25 19:04:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox...')
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox/dropbox/Authorize
HTTP_REFERER=http://localhost/proyectoDesarrollo/index.php/site/login
---
2012/10/25 19:05:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox...')
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox/dropbox/Authorize
---
2012/10/25 19:14:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox...')
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox/dropbox/Authorize
---
2012/10/25 19:20:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox...')
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox/dropbox/Authorize
---
2012/10/25 19:21:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox...')
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox/dropbox/Authorize
---
2012/10/25 19:22:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox...')
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox/dropbox/Authorize
---
2012/10/25 19:23:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'El sistema no ha podido encontrar la acción "dropbox" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php:484
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(271): CController->missingAction('dropbox')
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/dropbox...')
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox/dropbox/Authorize
---
2012/10/25 19:25:28 [error] [exception.Dropbox_Exception_NotFound] exception 'Dropbox_Exception_NotFound' with message 'Resource at uri: https://api-content.dropbox.com/1/thumbnails/dropbox/assets could not be found. No thumbnail available for the file type 'assets'
' in /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/extensions/dropbox/OAuth/Curl.php:128
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/extensions/dropbox/API.php(267): Dropbox_OAuth_Curl->fetch('https://api-con...', Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/protected/controllers/DropboxController.php(41): Dropbox_API->getThumbnail('/assets', 'small', 'dropbox')
#2 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/actions/CInlineAction.php(50): DropboxController->actionIndex()
#3 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#5 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(283): CController->run('index')
#7 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/web/CWebApplication.php(142): CWebApplication->runController('dropbox/index')
#8 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/framework/base/CApplication.php(162): CWebApplication->processRequest()
#9 /Applications/XAMPP/xamppfiles/htdocs/proyectoDesarrollo/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/proyectoDesarrollo/index.php/dropbox/index
---
2012/10/25 20:15:38 [error] [php] Constant consumerKey already defined (C:\wamp\www\ProyectoDesarrollo\protected\controllers\DropboxController.php:2)
Stack trace:
#0 C:\wamp\www\ProyectoDesarrollo\framework\web\CWebApplication.php(277): CWebApplication->createController()
#1 C:\wamp\www\ProyectoDesarrollo\framework\web\CWebApplication.php(142): CWebApplication->runController()
#2 C:\wamp\www\ProyectoDesarrollo\framework\base\CApplication.php(162): CWebApplication->processRequest()
#3 C:\wamp\www\ProyectoDesarrollo\index.php(13): CWebApplication->run()
REQUEST_URI=/ProyectoDesarrollo/index.php/dropbox
in C:\wamp\www\ProyectoDesarrollo\protected\controllers\DropboxController.php (2)
in C:\wamp\www\ProyectoDesarrollo\index.php (13)
